"""Rename foreign_movie to foreign

Revision ID: 73baa021a378
Revises: 
Create Date: 2025-09-05 14:44:46.117928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73baa021a378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign', sa.Boolean(), nullable=True))
        batch_op.drop_column('foreign_movie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign_movie', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('foreign')

    # ### end Alembic commands ###
